function Values = updateValues( DCresData, LinerValue, mosCurrents, diodeCurrents, CIp, LIp,...
                                plotnv,...
                                mosIndexInValues, mosIndexInmosCurrents, ...
                                dioIndexInValues, dioIndexIndiodeCurrents, ...
                                VIndexInValues, VIndexInDCres, ...
                                IIndexInValues, IIndexInValue, ...
                                RIndexInValues, RNodeIndexInDCresN1, RNodeIndexInDCresN2, ...
                                CIndexInValues, CIndexInCIp,...
                                LIndexInValues, LIndexInLIp,...
                                Values, nvNum, plotColNum)
        %% 节点电压信息
        Values((1 : nvNum), plotColNum) = DCresData(plotnv);
        %% 节点电流信息
        %mosIndexInValues\mosIndexInmosCurrents都是列向量 - 更改Values结果里要的mos管电流
        Values(mosIndexInValues, plotColNum) = Values(mosIndexInValues, plotColNum) .* mosCurrents(mosIndexInmosCurrents);
        %更改Values结果里要的diode管电流
        Values(dioIndexInValues, plotColNum) = Values(dioIndexInValues, plotColNum) .* diodeCurrents(dioIndexIndiodeCurrents);
        %更改Values结果里要的电源电压V
        Values(VIndexInValues, plotColNum) = Values(VIndexInValues, plotColNum) .* DCresData(VIndexInDCres);
        %更改Values结果里要的电源电流Is
        Values(IIndexInValues, plotColNum) = Values(IIndexInValues, plotColNum) .* LinerValue(IIndexInValue);
        %更改Values结果里要的电阻电流
        Values(RIndexInValues, plotColNum) = Values(RIndexInValues, plotColNum) .* (DCresData(RNodeIndexInDCresN1) - DCresData(RNodeIndexInDCresN2));
        %更改Values结果里要的电容电流
        Values(CIndexInValues, plotColNum) = Values(CIndexInValues, plotColNum) .* CIp(CIndexInCIp).';  %因为CIp为行向量, Values看每列
        %更改Values结果里要的电感电流
        Values(LIndexInValues, plotColNum) = Values(LIndexInValues, plotColNum) .* LIp(LIndexInLIp).';
end
