function summary = emptyHspiceWaveformSummary()
% EMPTYHSPICEWAVEFORMSUMMARY Return the default HSPICE waveform audit shape.
summary = struct( ...
    'available', false, ...
    'passed', false, ...
    'maxVoltageAbsError', NaN, ...
    'maxErrorSignal', "", ...
    'maxErrorTime', NaN, ...
    'signalSummaries', repmat(struct( ...
        'name', "", 'kind', "", 'domain', "", 'alignMode', "", ...
        'passed', false, 'maxAbsError', NaN, 'maxRelError', NaN, ...
        'maxPhaseDegError', NaN, 'maxErrorAxisValue', NaN), 0, 1), ...
    'missingSignals', strings(0, 1), ...
    'extraSignals', strings(0, 1), ...
    'notes', strings(0, 1));
end
