function comparison = failedComparison(message, backendReason)
% FAILEDCOMPARISON Build a comparison result for an execution failure.
comparison = struct( ...
    'passed', false, ...
    'maxAbsError', NaN, ...
    'maxRelError', NaN, ...
    'signalSummaries', repmat(struct( ...
        'name', "", 'kind', "", 'domain', "", 'alignMode', "", ...
        'passed', false, 'maxAbsError', NaN, 'maxRelError', NaN, ...
        'maxPhaseDegError', NaN, 'maxErrorAxisValue', NaN), 0, 1), ...
    'missingSignals', {{}}, ...
    'extraSignals', {{}}, ...
    'operatingPoint', struct('available', false, 'passed', false, 'nodeIds', zeros(0, 1), 'maxAbsError', NaN, 'maxRelError', NaN, 'maxErrorNode', NaN), ...
    'backend', "native", ...
    'backendReason', string(backendReason), ...
    'newtonSummary', struct(), ...
    'notes', string(message), ...
    'hspiceWaveform', spice.regression.emptyHspiceWaveformSummary(), ...
    'relaxedOnly', false);
end
