function entries = manifest(rootDir)
% MANIFEST Define the native-vs-legacy regression matrix.
% Each entry is the single source of truth for a regression case, its
% baseline, tolerances, HSPICE audit input, and whether the case is still a
% known expected failure while native accuracy work is in progress.
if nargin < 1 || strlength(string(rootDir)) == 0
    rootDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
end
rootDir = string(rootDir);

entries = [ ...
    makeEntry(rootDir, "bufferDC", "dc", "bufferDC.sp", baselineLis("buffer.lis"), baselineNone(), "dcDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierDC", "dc", "bjtAmplifierDC.sp", baselineLis("bjtamplifierdc.lis"), baselineNone(), "dcDefault", true) ...
    makeEntry(rootDir, "dbmixerDC", "dc", "dbmixerDC.sp", baselineLis("dbmixer.lis"), baselineNone(), "dcDefault", false) ...
    makeEntry(rootDir, "diftestDC", "dc", "diftestDC.sp", baselineLis("diftest.lis"), baselineNone(), "dcDefault", false) ...
    makeEntry(rootDir, "bufferAC", "ac", "bufferAC.sp", baselineLis("bufferac.lis"), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierAC", "ac", "bjtAmplifierAC.sp", baselineNone(), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "SmosAC", "ac", "SmosAC.sp", baselineLis("smosac.lis"), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "dbmixerAC", "ac", "dbmixerAC.sp", baselineLis("dbmixerac.lis"), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "bufferSweep", "dcsweep", "bufferSweep.sp", baselineLis("buffer.lis"), baselineNone(), "dcsweepDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierSweep", "dcsweep", "bjtAmplifierSweep.sp", baselineLis("bjtamplifierdc.lis"), baselineNone(), "dcsweepDefault", true) ...
    makeEntry(rootDir, "invertbufferSweep", "dcsweep", "invertbufferSweep.sp", baselineLis("inverterbuffer.lis"), baselineNone(), "dcsweepDefault", true) ...
    makeEntry(rootDir, "diftestSweep", "dcsweep", "diftestSweep.sp", baselineLis("diftest.lis"), baselineNone(), "dcsweepDefault", false) ...
    makeEntry(rootDir, "bufferTrans", "trans", "bufferTrans.sp", baselineLis("buffertrans.lis"), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierTrans", "trans", "bjtAmplifierTrans.sp", baselineLis("bjtamplifiertrans.lis"), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "dbmixerTrans", "trans", "dbmixerTrans.sp", baselineLis("dbmixertrans.lis"), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "diftestTrans", "trans", "diftestTrans.sp", baselineLis("diftesttrans.lis"), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "bufferTransDynamic", "trans", "bufferTrans.sp", baselineLis("buffertrans.lis"), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierTransDynamic", "trans", "bjtAmplifierTrans.sp", baselineLis("bjtamplifiertrans.lis"), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "bufferTransDynamicTR", "trans", "bufferTransDynamicTR.sp", baselineLis("buffertrans.lis"), baselineTr0("buffertrans.tr0"), "transientDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierTransDynamicTR", "trans", "bjtAmplifierTransDynamicTR.sp", baselineLis("bjtamplifiertrans.lis"), baselineTr0("bjtamplifiertrans.tr0"), "transientDefault", true) ...
    makeEntry(rootDir, "bufferShoot", "shoot", "bufferShoot.sp", baselineNone(), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "bjtAmplifierShoot", "shoot", "bjtAmplifierShoot.sp", baselineNone(), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "dbmixerShoot", "shoot", "dbmixerShoot.sp", baselineNone(), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "diftestShoot", "shoot", "diftestShoot.sp", baselineNone(), baselineNone(), "transientDefault", true) ...
    makeEntry(rootDir, "bufferPZ", "pz", "bufferPZ.sp", baselineNone(), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "RCPZ", "pz", "RCPZ.sp", baselineNone(), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "RCLPZ", "pz", "RCLPZ.sp", baselineNone(), baselineNone(), "acDefault", true) ...
    makeEntry(rootDir, "SmosPZ", "pz", "SmosPZ.sp", baselineNone(), baselineNone(), "acDefault", true) ...
    ];
end

function entry = makeEntry(rootDir, caseName, analysisType, netlistFile, operatingPointAudit, waveformAudit, toleranceName, expectedFail)
entry = struct( ...
    'caseName', string(caseName), ...
    'analysisType', string(analysisType), ...
    'netlistPath', fullfile(rootDir, 'examples', 'netlists', netlistFile), ...
    'baseline', "legacy", ...
    'operatingPointAudit', operatingPointAudit, ...
    'waveformAudit', waveformAudit, ...
    'probeSelection', "all", ...
    'toleranceProfile', toleranceProfile(toleranceName), ...
    'expectedFail', logical(expectedFail));
end

function audit = baselineLis(fileName)
audit = struct('kind', "hspiceLis", 'path', fullfile("fixtures", "hspice", fileName));
end

function audit = baselineTr0(fileName)
audit = struct('kind', "hspiceTr0", 'path', fullfile("fixtures", "hspice", fileName));
end

function audit = baselineNone()
audit = struct('kind', "none", 'path', "");
end

function profile = toleranceProfile(name)
switch string(name)
    case {"dcDefault", "dcsweepDefault"}
        profile = struct( ...
            'name', string(name), ...
            'nodeAbs', 1e-3, ...
            'currentAbs', 1e-6, ...
            'magnitudeRel', 0.02, ...
            'phaseAbsDeg', 2, ...
            'waveformAbs', 1e-2, ...
            'waveformCurrentAbs', 1e-4);
    case "acDefault"
        profile = struct( ...
            'name', string(name), ...
            'nodeAbs', 1e-3, ...
            'currentAbs', 1e-6, ...
            'magnitudeRel', 0.02, ...
            'phaseAbsDeg', 2, ...
            'waveformAbs', 1e-2, ...
            'waveformCurrentAbs', 1e-4);
    case "transientDefault"
        profile = struct( ...
            'name', string(name), ...
            'nodeAbs', 1e-3, ...
            'currentAbs', 1e-6, ...
            'magnitudeRel', 0.02, ...
            'phaseAbsDeg', 2, ...
            'waveformAbs', 1e-2, ...
            'waveformCurrentAbs', 1e-4);
    otherwise
        error('spice:regression:UnknownToleranceProfile', 'Unknown tolerance profile %s.', string(name));
end
end
