function writeCaseArtifacts(caseOutputDir, nativeResult, legacyResult, emitPlots)
% WRITECASEARTIFACTS Emit native and legacy SimulationResult artifacts.
if ~isempty(nativeResult)
    nativeResult.meta.acceptedByRegression = false;
    spice.output.emit(nativeResult, ...
        OutputDir=fullfile(caseOutputDir, 'native'), ...
        EmitPlots=emitPlots, ...
        WriteJSON=true, ...
        WriteMAT=true, ...
        WriteCSV=true);
end

if ~isempty(legacyResult)
    legacyResult.meta.acceptedByRegression = false;
    spice.output.emit(legacyResult, ...
        OutputDir=fullfile(caseOutputDir, 'legacy'), ...
        EmitPlots=emitPlots, ...
        WriteJSON=true, ...
        WriteMAT=true, ...
        WriteCSV=true);
end
end
