function options = defaultOptions()
options = struct( ...
    'InputKind', "file", ...
    'MatrixBackend', "sparse", ...
    'EmitPlots', false, ...
    'OutputDir', "", ...
    'ErrorTolerance', 1e-6, ...
    'TransientInitMethod', "Poweron", ...
    'TransientMethod', "BE", ...
    'TransientStepMode', "Fix", ...
    'WriteJSON', true, ...
    'WriteMAT', true, ...
    'WriteCSV', true);
end
