function attempt = attemptDynamicTransientStep( ...
        circuit, nativeCircuit, solver, options, previousContext, previousSolution, currentTime, stepTime, controller, reusableFullStep)
% ATTEMPTDYNAMICTRANSIENTSTEP Try one adaptive step and compute LTE metrics.
if nargin < 10
    reusableFullStep = [];
end

firstGuess = spice.analysis.native.chooseTransientInitialGuess(options, previousSolution, currentTime == 0);
usedCachedFullStep = spice.analysis.native.canReuseDynamicHalfStep(reusableFullStep, currentTime, stepTime, 0);
if usedCachedFullStep
    fullSolution = reusableFullStep.solution;
    fullStats = reusableFullStep.stats;
else
    [fullSolution, ~, fullStats] = spice.analysis.native.solveTransientOneStep( ...
        circuit, nativeCircuit, solver, options, previousContext, currentTime + stepTime, stepTime, firstGuess);
end

[halfSolution1, halfContext1, halfStats1] = spice.analysis.native.solveTransientOneStep( ...
    circuit, nativeCircuit, solver, options, previousContext, currentTime + 0.5 * stepTime, 0.5 * stepTime, firstGuess);
[halfSolution2, halfContext2, halfStats2] = spice.analysis.native.solveTransientOneStep( ...
    circuit, nativeCircuit, solver, options, halfContext1, currentTime + stepTime, 0.5 * stepTime, halfSolution1);
[acceptedSolution, acceptedContext] = spice.analysis.native.dynamicAcceptedTransientState( ...
    circuit, nativeCircuit, options, previousContext, fullSolution, halfSolution2, halfContext2, currentTime + stepTime, stepTime);

[lteMetric, tolerance, voltageErrorNorm, currentErrorNorm] = spice.analysis.native.dynamicErrorMetrics( ...
    fullSolution, halfSolution2, nativeCircuit, options, upper(string(options.TransientMethod)), controller.errorNodeIndices);
converged = fullStats.converged && halfStats1.converged && halfStats2.converged;
if upper(string(options.TransientMethod)) == "TR"
    accepted = converged && voltageErrorNorm <= controller.acceptErrorNorm && (~isfinite(currentErrorNorm) || currentErrorNorm <= 1e6);
else
    accepted = converged && lteMetric <= tolerance;
end

attempt = struct( ...
    'accepted', accepted, ...
    'solution', acceptedSolution, ...
    'nextContext', acceptedContext, ...
    'iterations', fullStats.iterations + halfStats1.iterations + halfStats2.iterations, ...
    'converged', converged, ...
    'mode', spice.analysis.native.dominantTransientMode([string(fullStats.mode), string(halfStats1.mode), string(halfStats2.mode)]), ...
    'lteMetric', lteMetric, ...
    'tolerance', tolerance, ...
    'voltageErrorNorm', voltageErrorNorm, ...
    'currentErrorNorm', currentErrorNorm, ...
    'usedCachedFullStep', usedCachedFullStep, ...
    'reusableHalfStep', struct( ...
        'currentTime', currentTime, ...
        'stepTime', 0.5 * stepTime, ...
        'solution', halfSolution1, ...
        'nextContext', halfContext1, ...
        'stats', halfStats1));
end
