function tf = canReuseDynamicHalfStep(reusableHalfStep, currentTime, stepTime, tolerance)
% CANREUSEDYNAMICHALFSTEP True when a cached half-step matches this interval.
tf = isstruct(reusableHalfStep) ...
    && isfield(reusableHalfStep, 'stepTime') ...
    && isfield(reusableHalfStep, 'currentTime') ...
    && abs(reusableHalfStep.stepTime - stepTime) <= max(tolerance, 1e-18) ...
    && abs(reusableHalfStep.currentTime - currentTime) <= max(tolerance, 1e-18);
end
